Repository Kakao-tech-campus-FE/step2-FE-kakao-shop, pull requests merged in 2023-08, with the labels that each got.

#262 부산대FE_박지호_5주차 과제
  kakao-store/.storybook/main.js
  kakao-store/.storybook/preview.js
  kakao-store/package-lock.json
  kakao-store/package.json
  kakao-store/src/App.js
  kakao-store/src/components/atoms/Card.jsx
  kakao-store/src/components/atoms/test/Box.stories.jsx
  kakao-store/src/components/atoms/test/Button.stories.jsx
  kakao-store/src/components/atoms/test/Input.stories.jsx
  kakao-store/src/components/atoms/test/Label.stories.jsx
  kakao-store/src/components/molecules/CartList.jsx
  kakao-store/src/components/molecules/OptionColums.jsx
  kakao-store/src/components/molecules/OrderList.jsx
  kakao-store/src/components/molecules/test/InputGroup.stories.jsx
  kakao-store/src/components/organisms/LoginForm.jsx
  kakao-store/src/components/template/MainProductTemplate.jsx
  kakao-store/src/components/template/OrderTemplate.jsx
  kakao-store/src/index.js
  kakao-store/src/layouts/RequiredAuthLayout.jsx
  kakao-store/src/pages/CartPage.jsx
  kakao-store/src/pages/OrderPage.jsx
  kakao-store/src/pages/OrderResultPage.jsx
  kakao-store/src/pages/ProductDetailPage.jsx
  kakao-store/src/services/cart.js
  kakao-store/src/services/index.js
  kakao-store/src/services/order.js
  kakao-store/src/stories/Button.jsx
  kakao-store/src/stories/Button.stories.js
  kakao-store/src/stories/Configure.mdx
  kakao-store/src/stories/Header.jsx
  kakao-store/src/stories/Header.stories.js
  kakao-store/src/stories/Page.jsx
  kakao-store/src/stories/Page.stories.js
  kakao-store/src/stories/assets/accessibility.png
  kakao-store/src/stories/assets/accessibility.svg
  kakao-store/src/stories/assets/addon-library.png
  kakao-store/src/stories/assets/assets.png
  kakao-store/src/stories/assets/context.png
  kakao-store/src/stories/assets/discord.svg
  kakao-store/src/stories/assets/docs.png
  kakao-store/src/stories/assets/figma-plugin.png
  kakao-store/src/stories/assets/github.svg
  kakao-store/src/stories/assets/share.png
  kakao-store/src/stories/assets/styling.png
  kakao-store/src/stories/assets/testing.png
  kakao-store/src/stories/assets/theming.png
  kakao-store/src/stories/assets/tutorials.svg
  kakao-store/src/stories/assets/youtube.svg
  kakao-store/src/stories/button.css
  kakao-store/src/stories/header.css
  kakao-store/src/stories/page.css
  kakao-store/tailwind.config.js
Labels: 부산대FE, 김도우멘토, 리뷰완료

#253 부산대FE_박동진_5주차 과제
  package-lock.json
  package.json
  public/images/logoKakao.png
  public/index.html
  public/manifest.json
  src/App.js
  src/components/atoms/Alert.jsx
  src/components/atoms/SelectBox.jsx
  src/components/atoms/Toast.jsx
  src/components/layouts/RequiredAuthLayout.jsx
  src/components/molecules/CartItem.jsx
  src/components/molecules/OptionColumn.jsx
  src/components/organisms/CartList.jsx
  src/components/organisms/GlobalNavBar.jsx
  src/components/organisms/LoginForm.jsx
  src/components/pages/CartPage.jsx
  src/components/pages/OrderComplatePage.jsx
  src/components/pages/OrderPage.jsx
  src/components/pages/ProductDetailPage.jsx
  src/components/templates/OrderTemplate.jsx
  src/components/templates/ProductDetailTemplate.jsx
  src/hooks/useInput.js
  src/index.js
  src/services/order.js
  src/store/slice/userSlice.js
  test/README.md
  test/orderTest/testOrder.js
  test/package-lock.json
  test/package.json
Labels: 부산대FE, 김도우멘토, 리뷰완료

#254 전남대FE_권동화_5주차_과제
  package-lock.json
  package.json
  src/apis/cart.js
  src/apis/index.js
  src/apis/order.js
  src/apis/product.js
  src/apis/user.js
  src/component/templates/OrderTemplete.jsx
  src/index.css
  src/pages/OrderPage.jsx
  src/store/slices/detailSlice.js
  src/store/slices/userSlice.js
  src/tailwind.config.js
  tailwind.config.js
Labels: 전남대FE, 김민수멘토

#266 전남대FE_곽민준_5주차 과제
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/components/atoms/CartItem.jsx
  src/components/molecules/Carousel.js
  src/components/molecules/CartList.jsx
  src/components/molecules/InputGroup.jsx
  src/components/molecules/SkeletonGroup.jsx
  src/components/organisms/LoginForm.jsx
  src/components/organisms/RegisterForm.jsx
  src/components/templates/MainProductTemplate.jsx
  src/components/templates/OrderCompleteTemplate.jsx
  src/components/templates/OrderTemplate.jsx
  src/constants/urls.js
  src/hooks/useInput.js
  src/index.js
  src/layouts/MainLayout.jsx
  src/pages/ErrorPage.jsx
  src/pages/OrderCompletePage.jsx
  src/pages/OrderPage.jsx
  src/services/cart.js
  src/services/index.js
  src/services/order.js
  src/services/product.js
  src/setupTests.js
  src/store/slices/productSlice.js
  src/utils/convert.js
  src/utils/errorcatch.js
Labels: 전남대FE, 김민수멘토

#267 전남대FE_김가연_5주차 과제
  src/components/templates/MainProductTemplate.jsx
  src/components/templates/OrderTemplate.jsx
  src/layout/RequiredAuthLayout.jsx
  src/pages/OrderCompletePage.jsx
  src/pages/OrderPage.jsx
  src/routes/RouterInfo.jsx
  src/routes/routes.js
  src/services/order.jsx
Labels: 전남대FE, 김민수멘토

#269 전남대FE_고민주_5주차 과제
  jest.config.js
  package-lock.json
  package.json
  src/App.jsx
  src/components/atoms/OrderItem.jsx
  src/components/molecules/CartList.jsx
  src/components/molecules/OptionColumn.jsx
  src/components/templates/MainProductTemplate.jsx
  src/components/templates/OrderSuccessTemplate.jsx
  src/components/templates/OrderTemplate.jsx
  src/index.js
  src/pages/CartPage.jsx
  src/pages/OrderPage.jsx
  src/pages/OrderSuccessPage.jsx.jsx
  src/pages/ProductDetailPage.jsx
  src/services/cart.js
  src/services/index.js
  src/services/order.js
  t
Labels: 전남대FE, 김민수멘토

#273 전남대FE_김단빈_5주차 과제
  step2-FE-kakao-shop/hw/src/App.js
  step2-FE-kakao-shop/hw/src/components/atoms/GNB.jsx
  step2-FE-kakao-shop/hw/src/components/molecules/CartList.jsx
  step2-FE-kakao-shop/hw/src/components/oTemplates/OrderTemplate.jsx
  step2-FE-kakao-shop/hw/src/components/organisms/HomeForm.jsx
  step2-FE-kakao-shop/hw/src/layouts/RequiredAuthLayout.jsx
  step2-FE-kakao-shop/hw/src/pages/DoneOrderPage.jsx
  step2-FE-kakao-shop/hw/src/pages/OrderPage.jsx
  step2-FE-kakao-shop/hw/src/services/order.js
  step2-FE-kakao-shop/hw/tailwind.config.js
Labels: 전남대FE, 김민수멘토

#275 전남대FE_경주원_5주차 과제
  src/api/instance.js
  src/api/orderAPI.js
  src/components/atoms/button/Button.jsx
  src/components/atoms/check-box/CheckBox.jsx
  src/components/molecules/order-product-option/OrderProductOption.jsx
  src/components/molecules/order-request/OrderRequest.jsx
  src/components/molecules/order-term-item/OrderTermItem.jsx
  src/components/organisms/order-agree-term/OrderAgreeTerm.jsx
  src/components/organisms/order-delivery/OrderDelivery.jsx
  src/components/organisms/order-product-column/OrderProductColumn.jsx
  src/constants/API.js
  src/constants/routes.js
  src/hooks/useGetOrderResult.js
  src/hooks/useGetProductByIdQuery.js
  src/hooks/usePostOrderMutation.js
  src/pages/Cart.jsx
  src/pages/Order.jsx
  src/pages/OrderResult.jsx
  src/router.jsx
  src/styles/GlobalStyle.js
Labels: 전남대FE, 김민수멘토

#328 부산대FE_이다빈_6주차 과제
  Dockerfile
  README.md
  default.conf
  package-lock.json
  package.json
  public/images/1.jpg
  public/images/10.jpg
  public/images/11.jpg
  public/images/12.jpg
  public/images/13.jpg
  public/images/14.jpg
  public/images/15.jpg
  public/images/2.jpg
  public/images/3.jpg
  public/images/4.jpg
  public/images/5.jpg
  public/images/6.jpg
  public/images/7.jpg
  public/images/8.jpg
  public/images/9.jpg
  src/App.js
  src/components/atoms/CartItem.jsx
  src/components/atoms/GNB.jsx
  src/components/atoms/OrderOptionItem.jsx
  src/components/atoms/SlimGNB.jsx
  src/components/molecules/CartList.jsx
  src/components/molecules/ProductCard.jsx
  src/components/molecules/ProductInformationColumn.jsx
  src/components/organisms/LoginForm.jsx
  src/components/organisms/RegisterForm.jsx
  src/components/templates/OrderResultTemplate.jsx
  src/components/templates/OrderTemplate.jsx
  src/pages/CartPage.jsx
  src/pages/Checkout.jsx
  src/pages/ErrorPage.jsx
  src/pages/HomePage.jsx
  src/pages/LoginPage.jsx
  src/pages/NotFoundPage.jsx
  src/pages/OrderPage.jsx
  src/pages/OrderSuccessPage.jsx
  src/pages/OrderTempPage.jsx
  src/pages/RegisterPage.jsx
  src/services/index.js
  src/services/order.js
Labels: 부산대FE, 김도우멘토, 리뷰완료

#337 부산대FE_김진우_6주차 과제
  .env
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/atoms/Carousel.jsx
  src/components/atoms/CartItem.jsx
  src/components/molecules/CartList.jsx
  src/components/molecules/Footer.jsx
  src/components/molecules/Gnb.jsx
  src/components/molecules/OptionColumn.jsx
  src/components/molecules/ProductCard.jsx
  src/components/molecules/ProductInformationColumn.jsx
  src/components/molecules/SkeletonCard.jsx
  src/components/organisms/SkeletonGrid.jsx
  src/components/templates/OrderCompleteTemplates.jsx
  src/components/templates/OrderTemplate.jsx
  src/components/templates/ProductDetailTemplate.jsx
  src/components/templates/ProductSection.jsx
  src/components/week1/Carousel.jsx
  src/pages/CartPage.jsx
  src/pages/ErrorPage.jsx
  src/pages/OrderCompletePage.jsx
  src/pages/OrderPage.jsx
  src/pages/ProductDetailPage.jsx
  src/services/cart.js
  src/services/index.js
  yarn.lock
Labels: 부산대FE, 김도우멘토, 리뷰완료

#306 부산대FE_박지호_6주차 과제
  README.md
  kakao-store/src/components/template/MainProductTemplate.jsx
  kakao-store/src/components/template/OrderTemplate.jsx
  kakao-store/src/pages/OrderResultPage.jsx
Labels: 부산대FE, 김도우멘토, 리뷰완료

#301 전남대FE_고민주_6주차_과제
  Dockerfile
  README.md
  default.conf
  goorm.manifest
  jest.config.js
  package-lock.json
  package.json
  public/assets/images/1.jpg
  public/assets/images/10.jpg
  public/assets/images/11.jpg
  public/assets/images/12.jpg
  public/assets/images/13.jpg
  public/assets/images/14.jpg
  public/assets/images/15.jpg
  public/assets/images/2.jpg
  public/assets/images/3.jpg
  public/assets/images/4.jpg
  public/assets/images/5.jpg
  public/assets/images/6.jpg
  public/assets/images/7.jpg
  public/assets/images/8.jpg
  public/assets/images/9.jpg
  src/App.jsx
  src/components/atoms/CartItem.jsx
  src/components/atoms/MyCarousel.jsx
  src/components/layouts/RequiredAuthLayout.jsx
  src/components/molecules/CartList.jsx
  src/components/molecules/GNB.jsx
  src/components/molecules/OptionColumn.jsx
  src/components/molecules/ProductCard.jsx
  src/components/molecules/ProductInformationColumn.jsx
  src/components/organisms/LoginForm.jsx
  src/components/organisms/RegisterForm.jsx
  src/components/organisms/StarRating.jsx
  src/components/templates/OrderSuccessTemplate.jsx
  src/components/templates/OrderTemplate.jsx
  src/pages/MainPage.jsx
  src/services/cart.js
  src/services/index.js
  t
  test/test.js
Labels: 전남대FE, 김민수멘토

#342 전남대FE_곽민준_6주차 과제
  .env
  Dockerfile
  README.md
  default.conf
  dist/output.css
  package-lock.json
  package.json
  src/App.js
  src/components/Breadcrumb.js
  src/components/Carousel.js
  src/components/Checklist.js
  src/components/RadioButton.js
  src/components/Toast.js
  src/components/ToggleButton.js
  src/components/atoms/Box.jsx
  src/components/atoms/Button.jsx
  src/components/atoms/CardSkeleton.jsx
  src/components/atoms/Counter.jsx
  src/components/atoms/Footer.jsx
  src/components/atoms/GNB.jsx
  src/components/atoms/Input.jsx
  src/components/atoms/Label.jsx
  src/components/atoms/OptionItem.jsx
  src/components/atoms/Photo.jsx
  src/components/molecules/CartList.jsx
  src/components/molecules/InputGroup.jsx
  src/components/molecules/OptionColumn.jsx
  src/components/molecules/SkeletonGroup.jsx
  src/components/organisms/LoginForm.jsx
  src/components/organisms/ProductGrid.jsx
  src/components/organisms/RegisterForm.jsx
  src/components/templates/OrderCompleteTemplate.jsx
  src/components/templates/OrderTemplate.jsx
  src/index.css
  src/pages/Cartpage.jsx
  src/pages/OrderCompletePage.jsx
  src/pages/OrderPage.jsx
  src/services/index.js
  src/store/sagas/product.js
  src/styles/atoms/GNB.css
  src/styles/atoms/Photo.css
  src/styles/organisms/ProductGrid.css
  src/styles/tailwind.css
  tailwind.config.js
Labels: 전남대FE, 김민수멘토

#350 부산대FE_전민지_5,6주차 과제
  Dockerfile
  README.md
  default.conf
  goorm.manifest
  mandu/package-lock.json
  mandu/package.json
  mandu/src/App.js
  mandu/src/App.test.js
  mandu/src/components/atoms/Dialog.js
  mandu/src/components/atoms/ListItems.js
  mandu/src/components/molecules/CartOptionCard.js
  mandu/src/components/molecules/OptionList.js
  mandu/src/components/molecules/OrderedTop.js
  mandu/src/components/molecules/PaymentOptionCard.js
  mandu/src/components/molecules/PaymentSectionCard.js
  mandu/src/components/molecules/ProductCard.js
  mandu/src/components/molecules/SelectedOptionList.js
  mandu/src/components/molecules/UserNav.js
  mandu/src/components/organisms/CartProductCard.js
  mandu/src/components/organisms/OrderedBody.js
  mandu/src/components/organisms/ProductInfo.js
  mandu/src/components/organisms/ProductWithOptionCard.js
  mandu/src/components/templates/MdLayOut.js
  mandu/src/const/index.js
  mandu/src/e2e.test.js
  mandu/src/pages/CartPage.js
  mandu/src/pages/ErrorPage.js
  mandu/src/pages/LoginPage.js
  mandu/src/pages/OrderedPage.js
  mandu/src/pages/PaymentPage.js
  mandu/src/pages/SignUpPage.js
  mandu/src/services/apis.js
  mandu/src/setupTests.js
  mandu/src/util/test-util.js
Labels: 이희찬멘토, 부산대FE

#331 부산대FE임연후 5,6주차 과제
  README.md
  src/api/dto.ts
  src/api/orderApi.ts
  src/assets/icon/HomeIcon.svg
  src/assets/svg.d.ts
  src/components/atoms/Card.tsx
  src/components/atoms/Checkbox.tsx
  src/components/atoms/InnerFlatCard.tsx
  src/components/atoms/OptionItem.tsx
  src/components/atoms/OrderedOption.tsx
  src/components/atoms/PageContainer.tsx
  src/components/atoms/PriceTag.tsx
  src/components/atoms/Title.tsx
  src/components/atoms/button/Button.interface.ts
  src/components/atoms/button/FilledButton.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/MainLayout.tsx
  src/components/molecules/CartItem.tsx
  src/components/molecules/OptionColumn.tsx
  src/components/molecules/ProductCard/ProductCard.tsx
  src/components/organisms/LoginForm.tsx
  src/components/organisms/RegisterForm.tsx
  src/components/pages/CartPage.tsx
  src/components/pages/LoginPage.tsx
  src/components/pages/OrderComplete.tsx
  src/components/pages/OrderPage.tsx
  src/components/pages/RegisterPage.tsx
  src/components/templates/OrderCompleteTemplate.tsx
  src/components/templates/OrderTemplate.tsx
  src/components/templates/ProductDetailPage/ProductDetailTemplate.tsx
  src/router/mainRouter.tsx
  src/tailwind.css
  tailwind.config.js
Labels: 이희찬멘토, 부산대FE

#323 부산대FE_김선우_6주차 과제(+5주차 과제)
  Dockerfile
  README.md
  default.conf
  package.json
  public/images/1.jpg
  public/images/10.jpg
  public/images/11.jpg
  public/images/12.jpg
  public/images/13.jpg
  public/images/14.jpg
  public/images/15.jpg
  public/images/2.jpg
  public/images/3.jpg
  public/images/4.jpg
  public/images/5.jpg
  public/images/6.jpg
  public/images/7.jpg
  public/images/8.jpg
  public/images/9.jpg
  src/App.js
  src/App.test.js
  src/components/atoms/Button.jsx
  src/components/atoms/Image.jsx
  src/components/atoms/Li.jsx
  src/components/atoms/NavUl.jsx
  src/components/atoms/OptionItems.jsx
  src/components/atoms/Photo.jsx
  src/components/molecules/LoginMenu.jsx
  src/components/molecules/Navigation.jsx
  src/components/molecules/OptionColumn.jsx
  src/components/molecules/ProductCard.jsx
  src/components/organisms/CartList.jsx
  src/components/organisms/GNB.jsx
  src/components/organisms/LoginForm.jsx
  src/components/organisms/RegisterForm.jsx
  src/components/pages/CartPage.jsx
  src/components/pages/MissedUrl.jsx
  src/components/pages/OrderCompletePage.jsx
  src/components/pages/OrderPage.jsx
  src/components/pages/ProductDetailPage.jsx
  src/components/templates/MainProductTemplate.jsx
  src/components/templates/OrderCompleteTemplate.jsx
  src/components/templates/OrderTemplate.jsx
  src/index.js
  src/layouts/RequiredAuthLayout.jsx
  src/robox.txt
  src/services/cart.js
  src/services/index.js
  src/services/order.js
Labels: 이희찬멘토, 부산대FE

#291 부산대FE_김은지_5, 6주차 과제
  .eslintrc.js
  Dockerfile
  README.md
  default.conf
  package-lock.json
  package.json
  public/images/1.jpg
  public/images/10.jpg
  public/images/11.jpg
  public/images/12.jpg
  public/images/13.jpg
  public/images/14.jpg
  public/images/15.jpg
  public/images/2.jpg
  public/images/3.jpg
  public/images/4.jpg
  public/images/5.jpg
  public/images/6.jpg
  public/images/7.jpg
  public/images/8.jpg
  public/images/9.jpg
  src/Router.tsx
  src/apis/productApi.ts
  src/components/atoms/Card.tsx
  src/components/atoms/LightButton.tsx
  src/components/atoms/LoginLink.tsx
  src/components/atoms/SimpleButton.tsx
  src/components/molecules/CartOptionItem.tsx
  src/components/molecules/Footer.tsx
  src/components/molecules/GNB.tsx
  src/components/molecules/OrderOptionItem.tsx
  src/components/molecules/ProductCard.tsx
  src/components/organisms/CartItem.tsx
  src/components/organisms/LoginForm.tsx
  src/components/organisms/OrderCompleteItem.tsx
  src/components/organisms/OrderItem.tsx
  src/components/organisms/ProductInformationColumn.tsx
  src/components/organisms/ProductOptionColumn.tsx
  src/components/organisms/RegisterForm.tsx
  src/components/templates/CartTemplate.tsx
  src/components/templates/NoProductTemplate.tsx
  src/components/templates/OrderCompleteTemplate.tsx
  src/components/templates/OrderTemplate.test.tsx
  src/components/templates/OrderTemplate.tsx
  src/dto/productDto.ts
  src/index.tsx
  src/layouts/SubLayout.tsx
  src/mocks/handlers.ts
  src/mocks/server.ts
  src/pages/LoginPage.tsx
  src/pages/OrderCompletePage.tsx
  src/pages/OrderPage.tsx
  src/setupTests.ts
  src/store/slices/userSlices.ts
  src/utils/convert.ts
  tailwind.config.js
Labels: 이희찬멘토, 부산대FE

#314 전남대FE_김민주_6주차 과제
  README.md
  kakao-shopping/src/apis/index.js
  kakao-shopping/src/components/atoms/Box.jsx
  kakao-shopping/src/components/atoms/Button.jsx
  kakao-shopping/src/components/atoms/Container.jsx
  kakao-shopping/src/components/atoms/Input.jsx
  kakao-shopping/src/components/atoms/Label.jsx
  kakao-shopping/src/components/atoms/Title.jsx
  kakao-shopping/src/components/organisms/LoginForm.jsx
  kakao-shopping/src/components/organisms/RegisterForm.jsx
  kakao-shopping/src/hooks/useInput.js
  kakao-shopping/src/index.js
  kakao-shopping/src/pages/LoginPage.jsx
  kakao-shopping/src/pages/RegisterPage.jsx
  kakao-shopping/src/services/api.js
  kakao-shopping/src/store/slices/userSlice.js
Labels: 전남대FE, 김민수멘토
